<?php
/* 
* Copyright (C) www.vtiger.com. All rights reserved.
* @license Proprietary
*/
$languageStrings = array(
	'LBL_PUBLISHER' => 'Publicador',
	'LBL_LICENSE' => 'Licencia',
	'LBL_PUBLISHED_ON' => 'Publicado el',
	'LBL_INSTALL' => 'Instalar',
	'LBL_UPGRADE' => 'Actualizar',
	'LBL_VERSION' => 'Versión',
	'LBL_DECLINE' => 'Declinar',
	'LBL_ACCEPT_AND_INSTALL' => 'Aceptar e Instalar',
	'LBL_OK' => 'OK',
	'LBL_EXTENSION_NOT_COMPATABLE' => 'Extensión no es Compatible',
	'LBL_INVALID_FILE' => 'Archivo Inválido',
	'LBL_NO_LICENSE_PROVIDED' => 'Licencia No Proporcionada',
	'LBL_INSTALLATION' => 'Instalación',
	'LBL_FAILED' => 'Fallida',
	'LBL_SUCCESSFULL' => 'Exitosa',
	'LBL_INSTALLATION_LOG' => 'Registro de Instalación',
	'LBL_UPDATED_MODULE' => ' fue actualizado exitosamente.',
	'LBL_UPDATING_MODULE' => 'Actualizando Módulo',
    
        //Extension Store translations
        'LBL_VTIGER_EXTENSION_STORE' => 'Tienda de Extensiones Vtiger',
        'LBL_SEARCH_FOR_AN_EXTENSION'  => 'Buscar una extensión..',
        'LBL_DOWNLOADS' => 'Descargas',
        'LBL_NO_EXTENSIONS_FOUND' => 'No se encontraron Extensiones',
        'LBL_REGISTER_TO_MARKET_PLACE' => 'Registrarse en la Tienda de Extensiones',
        'LBL_MARKETPLACE_REGISTRATION' => 'Registro en la Tienda de Extensiones',
        'LBL_MARKETPLACE_LOGIN' => 'Inicio de Sesión de la Tienda de Extensiones',
        'LBL_NEW_TO_MARKETPLCAE' => '¿ Nuevo en la Tienda de Extensiones ?',
        'LBL_CREATE_AN_ACCOUNT' => 'Crear cuenta nueva',
        'LBL_SETUP_CARD_DETAILS' => 'Configurar Detalles de Tarjeta de Crédito',
        'LBL_SETUP_CARD' => 'Configurar Tarjeta de Crédito',
        'LBL_CARD_NUMBER' => 'Número de Tarjeta',
        'LBL_EXP_MONTH' => 'Mes Exp',
        'LBL_EXP_YEAR' => 'Año Exp',
        'LBL_CVC_CODE' => 'Código CVC',
        'LBL_RESET' => 'Borrar',
        'LBL_EXTENSION_STORE' => 'Tienda de Extensiones',
        'LBL_INSTALLED' => 'Instalado',
        'LBL_UPDATE_CARD_DETAILS' => 'Actualizar Detalles de Tarjeta de Crédito',
        'LBL_BY' => 'por',
        'LBL_RATINGS' => 'Calificaciones',
        'LBL_DESCRIPTION' => 'Descripción',
        'LBL_AUTHOR_INFORMATION' => 'Información del Autor',
        'LBL_AUTHOR_NAME' => 'Nombre del Autor',
        'LBL_PHONE' => 'Teléfono',
        'LBL_EMAIL' => 'Correo',
        'LBL_SCREEN_SHOTS' => 'Imágenes',
        'LBL_CUSTOMER_RATINGS' => 'Calificaciones de los Clientes',
        'LBL_CUSTOMER_REVIEWS' => 'Opiniones de los Clientes',
        'LBL_WRITE_A_REVIEW' => 'Escribir una Opinión',
        'LBL_CUSTOMER_REVIEW' => 'Opinión del Cliente',
        'LBL_REVIEW' => 'Opinión',
        'LBL_CUSTOMERS_REVIEWED' => 'Clientes Calificaron',
        'LBL_SINGLE_CUSTOMER_REVIEWED' => 'Calificado por un Cliente',
        'LBL_INSTALLATION_FAILED' => 'Instalación Falló',
        'LBL_SUCCESSFULL_INSTALLATION' => 'Instalación Exitosa',
        'LBL_INSTALL_FROM_ZIP' => 'Instalar desde Zip',
        'LBL_MORE_DETAILS' => 'Más Detalles',
        'Install' => 'Instalar',
        'Upgrade' => 'Actualizar',
        'LBL_RATE_IT' => 'Calificar.',
        'LBL_UNINSTALL' => 'Desinstalar',
        'LBL_LAUNCH' => 'Abrir',
        'LBL_SIGN_UP_FOR_FREE' => 'Inscribirte gratis',
        'LBL_EMAIL_ADDRESS' => 'Dirección de correo',
        'LBL_FIRST_NAME' => 'Nombre',
        'LBL_LAST_NAME' => 'Apellidos',
        'LBL_COMPANY_NAME' => 'Nombre de compañía',
        'LBL_PASSWORD' => 'Contraseña',
        'LBL_CONFIRM_PASSWORD' => 'Confirmar contraseña',
        'LBL_REGISTER' => 'Registrar',
        'LBL_EXTENSION_STORE_LOGIN' => 'Inicio de Sesión de la Tienda de Extensiones',
        'LBL_REMEMBER_ME' => 'Recordarme',
        'LBL_TRY_IT' => 'Probarlo',
        'LBL_TRIAL_INSTALLED' => 'Versión de Prueba Instalado',
        'LBL_BUY' => 'Comprar ',
        'LBL_LOGIN_TO_MARKET_PLACE' => 'Iniciar Sesión en la Tienda de Extensiones',
        'LBL_LOGIN' => 'Iniciar sesión',
        'LBL_PHP_EXTENSION_LOADER_IS_NOT_AVAIABLE' => 'Por favor instale el cargador de extensiones',
        'LBL_INSTALL_EXTENSION_LOADER' => 'Instalar Cargador de Extensiones',
        'LBL_TO_CONTINUE_USING_EXTENSION_STORE' => 'Para continuar usando la Tienda de Extensiones por favor instala ',
        'LBL_DOWNLOAD' => 'Descargar',
        'LBL_COMPATIABLE_EXTENSION' => ' y habilítalo como zend_extension.',
        'LBL_MORE_DETAILS_ON_INSTALLATION' => 'Para más detalles sobre la instalación ',
        'LBL_READ_HERE' => 'leer aquí',
        'LBL_REVIEWS' => 'Opiniones',
        'LBL_SIGNUP_FOR_MARKET_PLACE' => 'Crear cuenta para la Tienda de Extensiones',
        'LBL_UNAUTHORIZED' => 'No autorizado',
        'LBL_EXPIRY_DATE'  => 'Fecha de Expiración',
    
        'firstname' => 'Nombre',
        'lastname' => 'Apellidos',
        'email' => 'Correo',
        'company' => 'Compañía',
        'Phone' => 'Teléfono',
        'Website' => 'Página Web',
        'LBL_SECURITY_CODE' => 'Código de Seguridad',
        'LBL_WHAT_IS_SECURITY_CODE' => '¿ Que es el Código de Seguridad ?',
        'LBL_CARD_NUMBER_PLACEHOLDER' => 'Número de 16 dígitos en tu tarjeta',
        'LBL_SECURITY_CODE_HELP_CONTENT' => 'El Número CVV (Valor de Verificación de Tarjeta) en su tarjeta de débito/crédito es un 
                                             número de 3 dígitos en el reverso de las tarjetas VISA®, MasterCard®, etc...',
);
$jsLanguageStrings = array(
  'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_THIS_EXTENSION'  => 'Por favor configure los detalles de su tarjeta para instalar esta extensión',
  'JS_UPDATE_CARD_DETAILS' => 'Actualizar Detalles de Tarjeta',
  'JS_ON' => 'en',
  'JS_RATINGS' => 'Calificaciones',
  'JS_INSTALLED' => 'Instalado',
  'JS_TRIAL_INSTALLED' => 'Versión de Prueba Instalada',
  'JS_PLEASE_INSTALL_EXTENSION_LOADER_TO_INSTALL_THIS_EXTENSION_FROM_BELOW_LINK' => 'Por favor instale el cargador de extensiones para
                                                                                    instalar esta extención desde el vínculo que está debajo',
  'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_INSTALLING_EXTENSION' => 'Por favor inicie sesión a la tienda de extensiones para instalar esta extensión',
  'JS_PLEASE_SETUP_CARD_DETAILS_TO_INSTALL_EXTENSION' => 'Por favor configure los detalles de la tarjeta de crédito para instalar esta extensión',
  'JS_PLEASE_LOGIN_TO_MARKETPLACE_FOR_UNINSTALLING_EXTENSION' => 'Por favor inicie sesión a la tienda de extensiones para desinstalar esta extensión',
  'JS_CARD_DETAILS_UPDATED' => 'Detalles de Tarjeta actualizados!',  
);
