<?php
/************************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array( 
	'Activity Type'                 => 'Tipo de Actividad'               ,
	'Call'                          => 'Llamada'                         ,
	'Completed'                     => 'Completado'                      ,
	'Daily'                         => 'Día(s)'                          ,
	'Deferred'                      => 'Pospuesto'                       ,
	'End Date' 						=> 'Fecha de Vencimiento'            ,
	'End Date & Time'               => 'Fecha y Hora de Vencimiento'     ,
	'first'                         => 'Primer'                          ,
	'ICAL_FORMAT' 					=> 'Formato iCal'                    ,
	'last'                          => 'Último'                          , 
	'LBL_ACTIVITY_TYPES'            => 'Tipos de Actividades'            ,
	'LBL_ADD_CALENDAR_VIEW' 	    => 'Agregar Vista de Calendario'     ,
	'LBL_ADD_EVENT'                 => 'Agregar Evento'                  ,
	'LBL_ADD_TASK'                  => 'Agregar Tarea Pendiente'         ,
	'LBL_ADDED_CALENDARS'           => 'Calendarios Agregados'           ,
	'LBL_CALENDAR_SETTINGS'         => 'Configuración del Calendario'    ,
	'LBL_CALENDAR_SHARING'          => 'Compartir Calendario'            ,
	'LBL_CALENDAR_VIEW'             => 'Vista de Calendario'             ,
	'LBL_CALL'                      => 'Llamada'                         ,
	'LBL_CHANGE_OWNER'              => 'Cambiar Propietario'             ,
	'LBL_CONTACTS_BIRTH_DAY'        => 'Fecha de Nacimiento'             ,
	'LBL_CONTACTS_SUPPORT_END_DATE' => 'Fecha de Fin de Soporte'         ,
	'LBL_DAY0'                      => 'Domingo'                         , 
	'LBL_DAY1'                      => 'Lunes'                           ,
	'LBL_DAY2'                      => 'Martes'                          , 
	'LBL_DAY3'                      => 'Miércoles'                       , 
	'LBL_DAY4'                      => 'Jueves'                          , 
	'LBL_DAY5'                      => 'Viernes'                         , 
	'LBL_DAY6'                      => 'Sábado'                          ,
	'LBL_DAY_OF_THE_MONTH'          => 'Día del mes'                     ,
	'LBL_DEFAULT_EVENT_DURATION'    => 'Duración de evento por defecto'  ,
	'LBL_DEFAULT_STATUS_TYPE'       => 'Estatus y Tipo Predeterminados'  ,
	'LBL_DELETE_CALENDAR' 			=> 'Eliminar Calendario'             ,
	'LBL_EDITING_CALENDAR_VIEW' 	=> 'Editar Vista de Calendario'      ,
	'LBL_EDIT_COLOR' 				=> 'Editar color'                    ,
	'LBL_EVENT'                     => 'Evento'                          ,
	'LBL_EVENT_INFORMATION'         => 'Detalles del Evento'             ,
	'LBL_EVENT_OR_TASK'             => 'Evento / Tarea Pendiente'        ,
	'LBL_EVENTS'                    => 'Eventos'                         ,
	'LBL_FINISH' 					=> 'Terminar'						 ,
	'LBL_IMPORT_RECORDS' 			=> 'Importar Registros'              ,
	'LBL_LAST_IMPORT_UNDONE' 		=> 'Se Deshizo Su Última Importación',
	'LBL_MINUTES'                   => 'Minutos'                         ,
	'LBL_ON'                        => 'en'                              ,
	'LBL_OTHER_EVENTS'              => 'Otros Eventos'                   ,
	'LBL_RECORDS_LIST'              => 'Vista de Lista'                  ,
	'LBL_RESULT' 					=> 'Resultado',
	'LBL_SELECT_ACTIVITY_TYPE' 		=> 'Seleccionar Tipo de Actividad'   ,
	'LBL_SELECT_CALENDAR_COLOR' 	=> 'Seleccione Color del Calendario' ,
	'LBL_SELECT_USERS'              => 'Seleccionar usuarios'            ,
	'LBL_SELECT_USER_CALENDAR' 		=> 'Seleccione Calendario de Usuario',
	'LBL_SHARED_CALENDAR'           => 'Calendario Compartido'           ,
	'LBL_STATUS'                    => 'Estatus'                         ,
	'LBL_TASK'                      => 'Tarea Pendiente'                 ,
	'LBL_TASKS'						=> 'Tareas Pendientes'               ,
	'LBL_TASK_INFORMATION'          => 'Detalles de la Tarea Pendiente'  ,
	'LBL_TODOS'                     => 'Tareas Pendientes'               ,
	'LBL_TOTAL_EVENTS_IMPORTED' 	=> 'No. de Eventos Importados Exitosamente' ,
	'LBL_TOTAL_EVENTS_SKIPPED' 		=> 'No. de Eventos Omitidos ya que faltaba uno o más campos requeridos',
	'LBL_TOTAL_TASKS_IMPORTED' 		=> 'No. of Tareas Pendientes Importadas Exitosamente',
	'LBL_TOTAL_TASKS_SKIPPED' 		=> 'No. de Tareas Pendinetes Omitidas ya que faltaba uno o más campos requeridos',
	'LBL_TYPE'                      => 'Tipo'                            ,
	'LBL_UNDO_LAST_IMPORT' 			=> 'Deshacer Última Importación'     ,
	'Location'                      => 'Lugar'                           ,
	'Medium'                        => 'Medio'                           ,
	'Meeting'                       => 'Reunión'                         ,
	'Monthly'                       => 'Mes(es)'                         ,
	'Not Started'                   => 'No Iniciada'                     ,
	'Pending Input'                 => 'Faltan Datos'                    ,
	'Planned'                       => 'Planeado'                        ,
	'Send Notification'             => 'Enviar notificación'             ,
	'SINGLE_Calendar'               => 'Tarea Pendiente'                 ,
	'SINGLE_Events' 				=> 'Evento'                          ,
	'Start Date & Time'             => 'Fecha y Hora de Inicio'          ,
	'Subject'                       => 'Asunto'                          ,
	'Task'                          => 'Tarea Pendiente'                 ,
	'Tasks' 						=> 'Tareas Pendientes'               ,
	'Weekly'                        => 'Semana(s)'                       ,
	'Yearly'                        => 'Año'                             ,

	//Valores de Lista Desplegable "Estatus del Evento"
	'Held'                          => 'Llevada a Cabo'                  ,
	'Not Held'                      => 'No Llevada a Cabo'               ,

	
	
	
);
$jsLanguageStrings = array(
	'LBL_ADD_EVENT_TASK'           						 => 'Agregar Evento / Tarea'                              			, 
	'JS_TASK_IS_SUCCESSFULLY_ADDED_TO_YOUR_CALENDAR' 	 => 'Tarea Pendiente añadida exitosamente a tu Calendario'          , 
	'LBL_CANT_SELECT_CONTACT_FROM_LEADS' 				 => 'No se puede seleccionar Contactos relaciones para Prospectos'  ,
	'JS_CALENDAR_VIEW_COLOR_UPDATED_SUCCESSFULLY' 		 => 'Color de Vista de de Calendario actualizado correctamente'     ,
	'JS_CALENDAR_VIEW_DELETE_CONFIRMATION' 				 => '¿Está seguro de que desea eliminar esta Vista de Calendario?'  ,
	'JS_CALENDAR_VIEW_ADDED_SUCCESSFULLY' 				 => 'Vista de calendario agregada correctamente'                    ,
	'JS_CALENDAR_VIEW_DELETED_SUCCESSFULLY' 			 => 'Vista de calendario eliminada correctamente'                   ,
	'JS_EDIT_CALENDAR' 									 => 'Editar Calendario'                                             , 
    	'JS_FUTURE_EVENT_CANNOT_BE_HELD' 				 => 'No se puede establecer un evento futuro como Llevada a Cabo'   ,
    'JS_NO_CALENDAR_VIEWS_TO_ADD' 						 => 'No hay Vista de Calendario para agregar'					    ,
        'JS_NO_DELETE_PERMISSION' 						 => 'No tiene permiso para eliminar entradas del calendario.'		, 
        'JS_NO_EDIT_PERMISSION' 						 => 'No tiene permiso para modificar entradas del calendario.'		, 
        'JS_RECORD_DELETED' 							 => 'Entrada del Calendario eliminada exitosamente'					, 
	
	//Calendar view label translation
	'LBL_DAY' => 'Día',
	'LBL_MONTH' => 'Mes',
	'LBL_TODAY' => 'Hoy',
	'LBL_WEEK' => 'Semana',
	
	'LBL_SUNDAY' => 'Domingo',
	'LBL_MONDAY' => 'Lunes',
	'LBL_TUESDAY' => 'Martes',
	'LBL_WEDNESDAY' => 'Miércoles',
	'LBL_THURSDAY' => 'Jueves',
	'LBL_FRIDAY' => 'Viernes',
	'LBL_SATURDAY' => 'Sábado',
	
	'LBL_SUN' => 'Dom',
	'LBL_MON' => 'Lun',
	'LBL_TUE' => 'Mar',
	'LBL_WED' => 'Mie',
	'LBL_THU' => 'Jue',
	'LBL_FRI' => 'Vie',
	'LBL_SAT' => 'Sab',
	
	'LBL_JANUARY' => 'Enero',
	'LBL_FEBRUARY' => 'Febrero',
	'LBL_MARCH' => 'Marzo',
	'LBL_APRIL' => 'Abril',
	'LBL_MAY' => 'Mayo',
	'LBL_JUNE' => 'Junio',
	'LBL_JULY' => 'Julio',
	'LBL_AUGUST' => 'Agosto',
	'LBL_SEPTEMBER' => 'Septiembre',
	'LBL_OCTOBER' => 'Octubre',
	'LBL_NOVEMBER' => 'Noviembre',
	'LBL_DECEMBER' => 'Diciembre',
	
	'LBL_JAN' => 'Ene',
	'LBL_FEB' => 'Feb',
	'LBL_MAR' => 'Mar',
	'LBL_APR' => 'Abr',
	'LBL_MAY' => 'May',
	'LBL_JUN' => 'Jun',
	'LBL_JUL' => 'Jul',
	'LBL_AUG' => 'Ago',
	'LBL_SEP' => 'Sep',
	'LBL_OCT' => 'Oct',
	'LBL_NOV' => 'Nov',
	'LBL_DEC' => 'Dic',
	
	'LBL_ALL_DAY' => 'Todo el día',
	'Mobile Call' => 'Llamar al celular',
	//End
	
	
	'JS_NO_CALENDAR_VIEWS_TO_ADD' => 'Sin vista de calendario para agregar',
	
);
