<?php
/************************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'Events'                       => 'Eventos'                     , 
	'SINGLE_Events'                => 'Evento'                      , 
	'LBL_ADD_RECORD'               => 'Agregar Evento'              , 
	'LBL_RECORDS_LIST'             => 'Vista de Lista'              , 
	'LBL_EVENTS'                   => 'Eventos'                     , 
	'LBL_TODOS'                    => 'Tareas Pendientes'           , 
	'LBL_HOLD_FOLLOWUP_ON'         => 'Dar Seguimiento El'          ,
    'LBL_CREATE_FOLLOWUP_EVENT'    => 'Crear Evento de Seguimiento' ,
	'LBL_EVENT_INFORMATION'        => 'Detalle del evento'          , 
	'LBL_RECURRENCE_INFORMATION'   => 'Detalles de recurrencia'     , 
	'LBL_RELATED_TO'               => 'Relacionado a'               , 
	'Start Date & Time'            => 'Fecha y Hora de Inicio'      , 
	'Recurrence'                   => 'Repetir'                     , 
	'Send Notification'            => 'Enviar notificación'         ,
	'Location'                     => 'Lugar'                       , 
	'Send Reminder'                => 'Enviar Recordatorio por Correo con Anticipación', 
	'End Date & Time'              => 'Fecha y Hora de Vencimiento' , 
	'Activity Type'                => 'Tipo de Actividad'           , 
	'Visibility'                   => 'Visibilidad'                 , 
	'Private'                      => 'Privado'                     , 
	'Public'                       => 'Publico'                     , 
	'Call'                         => 'Llamada'                     , 
	'Meeting'                      => 'Reunión'                     ,
	'Mobile Call'                  => 'Llamada al celular'          ,
	'Planned'                      => 'Planeada'                    , 
	'Held'                         => 'Llevada a Cabo'              , 
	'Not Held'                     => 'No Llevada a Cabo'           , 
	'LBL_DAYS'                     => 'Días'                        , 
	'LBL_HOURS'                    => 'Horas'                       , 
	'LBL_DAYS_TYPE'                => 'Día(s)'                      , 
	'LBL_WEEKS_TYPE'               => 'Semana(s)'                   , 
	'LBL_MONTHS_TYPE'              => 'Mes(es)'                     , 
	'LBL_YEAR_TYPE'                => 'Año'                         , 
	'LBL_FIRST'                    => 'Primer'                      , 
	'LBL_LAST'                     => 'Último'                      , 
	'LBL_SM_SUN'                   => 'Dom'                         , 
	'LBL_SM_MON'                   => 'Lun'                         , 
	'LBL_SM_TUE'                   => 'Mar'                         , 
	'LBL_SM_WED'                   => 'Mier'                        , 
	'LBL_SM_THU'                   => 'Jue'                         , 
	'LBL_SM_FRI'                   => 'Vie'                         , 
	'LBL_SM_SAT'                   => 'Sab'                         , 
	'LBL_DAY0'                     => 'Domingo'                     , 
	'LBL_DAY1'                     => 'Lunes'                       , 
	'LBL_DAY2'                     => 'Martes'                      , 
	'LBL_DAY3'                     => 'Miércoles'                   , 
	'LBL_DAY4'                     => 'Jueves'                      , 
	'LBL_DAY5'                     => 'Viernes'                     , 
	'LBL_DAY6'                     => 'Sábado'                      , 
	'Daily'                        => 'Día(s)'                      , 
	'Weekly'                       => 'Semana(s)'                   , 
	'Monthly'                      => 'Mes(es)'                     , 
	'Yearly'                       => 'Año'                         , 
	'LBL_REPEATEVENT'              => 'Una vez en cada'             , 
	'LBL_UNTIL'                    => 'Hasta el'                    , 
	'LBL_DAY_OF_THE_MONTH'         => 'Día del mes'                 , 
	'LBL_ON'                       => 'en'                          , 
	'LBL_CALENDAR_VIEW'            => 'Vista de Calendario'         , 
	'LBL_INVITE_USER_BLOCK'        => 'Invitar'                     , 
	'LBL_INVITE_USERS'             => 'Invitar Usuarios'            ,
	'Busy'                         => 'Ocupado'                     ,
	'INVITATION'                   => 'Invitación '                 ,

	//Valores de la lista desplegable "Prioridad" 
	'High'                         => 'Alta'                        ,
    'Medium'                       => 'Media'                       , 
    'Low'                          => 'Baja'                        ,
);