<?php
/************************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'HelpDesk'                     => 'Casos', 
	'SINGLE_HelpDesk'              => 'Caso', 
	'LBL_ADD_RECORD'               => 'Agregar Caso', 
	'LBL_RECORDS_LIST'             => 'Lista de Casos', 
	'LBL_TICKET_INFORMATION'       => 'Información del Caso', 
	'LBL_TICKET_RESOLUTION'        => 'Solución Propuesta', 
	'Ticket No'                    => 'Número de Caso', 
	'Severity'                     => 'Importancia', 
	'Update History'               => 'Historial de Actualizaciones', 
	'Hours'                        => 'Horas', 
	'Days'                         => 'Días', 
	'Title'                        => 'Título', 
	'Solution'                     => 'Solución', 
	'From Portal'                  => 'Proviene del Portal', 
	'Big Problem'                  => 'Problema Grave', 
	'Small Problem'                => 'Problema Menor', 
	'Other Problem'                => 'Otro Tipo de Problema', 
	'Normal'                       => 'Normal', 
	'High'                         => 'Alta', 
	'Urgent'                       => 'Urgente', 
	'Minor'                        => 'Menor', 
	'Major'                        => 'Mayor', 
	'Feature'                      => 'Característica', 
	'Critical'                     => 'Crítica', 
	'Open'                         => 'Abierto', 
	'Wait For Response'            => 'Esperando Respuesta', 
	'Closed'                       => 'Cerrado', 
	'LBL_STATUS'                   => 'Estatus',
	'LBL_SEVERITY'                 => 'Importancia', 
	'LBL_CONVERT_FAQ'              => 'Convertir a FAQ', 
	'LBL_RELATED_TO'               => 'Relacionado Con',

	//added to support i18n in ticket mails
	'Hi'						   => 'Hola',
	'Dear'						   => 'Estimado(a)',
	'LBL_PORTAL_BODY_MAILINFO' 	   => 'El Caso ha sido',
	'LBL_DETAIL' 				   => ', los detalles son:',
	'LBL_REGARDS'				   => 'Atentamente,',
	'LBL_TEAM'					   => 'Equipo de Soporte al Cliente',
	'LBL_TICKET_DETAILS' 		   => 'Detalles de Caso',
	'LBL_SUBJECT'				   => 'Asunto : ',
	'created'					   => 'creado',
	'replied'					   => 'respondido',
	'reply'						   => 'Hay una respuesta al caso: ',
	'customer_portal'			   => ' en el Portal de Clientes de AeroSolar México. ',
	'link' 						   => 'Puede utilizar el siguiente enlace para ver las respuestas del caso en referencia:',
	'Thanks' 					   => 'Gracias',
	'Support_team'				   => 'Equipo de Soporte al Cliente',
	'The comments are' 			   => 'Los comentarios son',
	'Ticket Title' 				   => 'Título del Caso',
	'Re'                           => 'Re :',

	//this label for customerportal.
	'LBL_STATUS_CLOSED' 		   => 'Closed',//Do not convert this label. This is used to check the status. If the status 'Closed' is changed in vtigerCRM server side then you have to change in customerportal language file also.
	'LBL_STATUS_UPDATE' 		   => 'Estatus del Caso actualizado a',
	'LBL_COULDNOT_CLOSED'		   => 'El Caso no pudo ser',
	'LBL_CUSTOMER_COMMENTS' 	   => 'EL Cliente ha incluido la siguiente información a su respuesta:',
	'LBL_RESPOND' 				   => 'Por favor responda al Caso lo más pronto posible.',
	'LBL_REGARDS'				   => 'Saludos Cordiales,',
	'LBL_SUPPORT_ADMIN'			   => 'Administrador de Soporte al Cliente',
	'LBL_RESPONDTO_TICKETID'	   => 'Responder al Caso No.',
	'LBL_RESPONSE_TO_TICKET_NUMBER'=> 'Respuesta al Caso No.',
	'LBL_CUSTOMER_PORTAL' 		   => 'en el Portal del Cliente - URGENTE',
	'LBL_LOGIN_DETAILS' 		   => 'Sus datos de Acceso al Portal del Cliente son:',
	'LBL_MAIL_COULDNOT_SENT' 	   => 'No se pudo enviar el correo',
	'LBL_USERNAME' 				   => 'Nombre de Usuario:',
	'LBL_PASSWORD'				   => 'Contraseña:',
	'LBL_SUBJECT_PORTAL_LOGIN_DETAILS' => 'Datos de Acceso al Portal del Cliente',
	'LBL_GIVE_MAILID' 			   => 'Por favor introduzca su dirección de correo',
	'LBL_CHECK_MAILID'			   => 'Por favor revise su dirección de email para el Portal del Cliente',
	'LBL_LOGIN_REVOKED'			   => 'Acceso revocado, consulte con su administrador.',
	'LBL_MAIL_SENT'				   => 'Se le ha enviado un correo con los datos de Acceso al Portal del Cliente al correo con el que se registró',
	'LBL_ALTBODY' 				   => 'Este es el mensaje de correo para los clientes que no soportan HTML',
	'HelpDesk ID' 			  	   => 'Número de Caso',
	'Ticket ID'					   => 'Número de Caso',
	'LBL_TICKET_NUMBER'			   => 'Número de Caso',
	'Contact Name'                 => 'Nombre del Contacto',
	'Related To'                   => 'Nombre de la Cuenta',
);
