<?php
/************************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.0
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/
$languageStrings = array(
	'LBL_IMPORT_STEP_1'                         => 'Paso 1', 
	'LBL_IMPORT_STEP_1_DESCRIPTION'             => 'Selecciona Archivo', 
	'LBL_IMPORT_SUPPORTED_FILE_TYPES'           => 'Tipo(s) de Archivo Aceptados: .CSV, .VCF', 
	'LBL_IMPORT_STEP_2'                         => 'Paso 2', 
	'LBL_IMPORT_STEP_2_DESCRIPTION'             => 'Especifica el Formato', 
	'LBL_FILE_TYPE'                             => 'Tipo de Archivo', 
	'LBL_CHARACTER_ENCODING'                    => 'Codificación de Caracteres', 
	'LBL_DELIMITER'                             => 'Delimitador', 
	'LBL_HAS_HEADER'                            => 'Tiene Encabezados', 
	'LBL_IMPORT_STEP_3'                         => 'Paso 3', 
	'LBL_IMPORT_STEP_3_DESCRIPTION'             => 'Manejo de Registros Duplicados', 
	'LBL_IMPORT_STEP_3_DESCRIPTION_DETAILED'    => 'Seleccione esta opción para habilitar y configurar el control de duplicados', 
	'LBL_SPECIFY_MERGE_TYPE'                    => 'Selecciona cómo se han de manejar los registros duplicados', 
	'LBL_SELECT_MERGE_FIELDS'                   => 'Selecciona los campos coincidentes para encontrar duplicados', 
	'LBL_AVAILABLE_FIELDS'                      => 'Campos Disponibles', 
	'LBL_SELECTED_FIELDS'                       => 'Campos Que Serán Comparados', 
	'LBL_NEXT_BUTTON_LABEL'                     => 'Siguiente', 
	'LBL_IMPORT_STEP_4'                         => 'Paso 4', 
	'LBL_IMPORT_STEP_4_DESCRIPTION'             => 'Asigna las Columnas a Campos del Módulo', 
	'LBL_FILE_COLUMN_HEADER'                    => 'Encabezado', 
	'LBL_ROW_1'                                 => 'Fila 1', 
	'LBL_CRM_FIELDS'                            => 'Campos del CRM', 
	'LBL_DEFAULT_VALUE'                         => 'Valor por defecto', 
	'LBL_SAVE_AS_CUSTOM_MAPPING'                => 'Guardar como Asignación Personalizada', 
	'LBL_IMPORT_BUTTON_LABEL'                   => 'Importar', 
	'LBL_RESULT'                                => 'Resultado', 
	'LBL_TOTAL_RECORDS_IMPORTED'                => 'Registros importados exitosamente', 
	'LBL_NUMBER_OF_RECORDS_CREATED'             => 'Registros creados', 
	'LBL_NUMBER_OF_RECORDS_UPDATED'             => 'Registros sobreescritos', 
	'LBL_NUMBER_OF_RECORDS_SKIPPED'             => 'Registros omitidos', 
	'LBL_NUMBER_OF_RECORDS_MERGED'              => 'Registros combinados', 
	'LBL_TOTAL_RECORDS_FAILED'                  => 'Registros que no se pudieron importar', 
	'LBL_IMPORT_MORE'                           => 'Importar Más', 
	'LBL_VIEW_LAST_IMPORTED_RECORDS'            => 'Últimos Registros Importados', 
	'LBL_UNDO_LAST_IMPORT'                      => 'Deshacer Última Importación', 
	'LBL_FINISH_BUTTON_LABEL'                   => 'Terminar', 
	'LBL_UNDO_RESULT'                           => 'Resultado de Deshacer la Importación', 
	'LBL_TOTAL_RECORDS'                         => 'Número total de registros'  , 
	'LBL_NUMBER_OF_RECORDS_DELETED'             => 'Número total de registros eliminados', 
	'LBL_OK_BUTTON_LABEL'                       => 'Ok', 
	'LBL_IMPORT_SCHEDULED'                      => 'Importación Planificada', 
	'LBL_RUNNING'                               => 'En ejecución', 
	'LBL_CANCEL_IMPORT'                         => 'Cancelar Importación', 
	'LBL_ERROR'                                 => 'Error', 
	'LBL_CLEAR_DATA'                            => 'Limpiar Datos', 
	'ERR_UNIMPORTED_RECORDS_EXIST'              => 'No se pueden importar más datos en este lote. Por favor inicie una importación nueva.', 
	'ERR_IMPORT_INTERRUPTED'                    => 'La importación actual ha sido interrumpida. Por favor intente nuevamente más tarde', 
	'ERR_FAILED_TO_LOCK_MODULE'                 => 'No se ha podido bloquear el módulo para la importación. Inténtelo de nuevo más tarde.', 
	'LBL_SELECT_SAVED_MAPPING'                  => 'Seleccionar Asignación Guardada', 
	'LBL_IMPORT_ERROR_LARGE_FILE'               => 'Error al importar el archivo por tamaño excedido', 
	'LBL_FILE_UPLOAD_FAILED'                    => 'Fallo Carga del Archivo', 
	'LBL_IMPORT_CHANGE_UPLOAD_SIZE'             => 'Cambia el límite permitido de tamaño de archivo', 
	'LBL_IMPORT_DIRECTORY_NOT_WRITABLE'         => 'Directorio de importación no escribible', 
	'LBL_IMPORT_FILE_COPY_FAILED'               => 'Falló la Copia de archivo importado', 
	'LBL_INVALID_FILE'                          => 'Archivo inválido', 
	'LBL_NO_ROWS_FOUND'                         => 'No se encontraron registros', 
	'LBL_SCHEDULED_IMPORT_DETAILS'              => 'La importación ha sido programada e iniciará en los próximos 15 minutos. Recibirás un correo una vez que la importación haya 
													finalizado. <br><br>Por favor asegúrese que el servidor de correo de salida y su dirección de correo estén configurados 
													correctamente para recibir notificaciónes por correo.', 
	'LBL_DETAILS'                               => 'Detalles', 
	'skipped'                                   => 'Registros Omitidos', 
	'failed'                                    => 'Registros Que No Se Pudieron Importar', 
        'Skip'                                  => 'Omitir',
        'Overwrite'                             => 'Sobrescribir',
        'Merge'                                 => 'Combinar',
);