<?php
/*+**********************************************************************************
 * The contents of this file are subject to the vtiger CRM Public License Version 1.1
 * ("License"); You may not use this file except in compliance with the License
 * The Original Code is:  vtiger CRM Open Source
 * The Initial Developer of the Original Code is vtiger.
 * Portions created by vtiger are Copyright (C) vtiger.
 * All Rights Reserved.
 ************************************************************************************/

$languageStrings = Array (
	'JSLBL_Body_Cannot_Be_Empty' 				=> 'Contenido no puede estar vacío',
	'LBL_10_MIN' 								=> '10 Minutos',
	'LBL_5_MIN' 								=> '5 Minutos',
	'LBL_Account_Password'     					=> 'contraseña de la cuenta',
	'LBL_ACCOUNT_TYPE' 							=> 'Tipo de Cuenta',
	'LBL_ACTIONS'         						=> 'Acciones',
    'LBL_ADD' 									=> 'Agregar',
	'LBL_ALLMAILS' 								=> 'Todos los Correos',
	'LBL_Associate'       						=> 'Asociar',
	'LBL_ATTACHMENTS'  							=> 'Archivo adjunto:',
	'LBL_Attachments' 							=> 'Archivos adjuntos',
	'LBL_BCC'         							=> 'BCC',
	'LBL_CANCEL_BUTTON_LABEL' 					=> 'Cancelar',
	'LBL_Cancel'          						=> 'Cancelar',
	'LBL_CC'          							=> 'CC',
	'LBL_Certificate_Validations' 				=> 'Validaciones de Certificados',
    'LBL_CHOOSE_EXISTING_FOLDER' 				=> 'Selecciona una carpeta existente',
    'LBL_CHOOSE_FOLDER' 						=> 'Copias de los correos enviados para esta cuenta serán guardados en esta carpeta.',
    'LBL_CHOOSE_FOLDER_DESC' 					=> 'Copias de los correos enviados para esta cuenta serán guardados en la carpeta predeterminada 
    												<b>Correos Enviados</b>.<br><br>Si desea cambiar la carpeta predeterminada de correos enviados, 
    												después de crear el buzón haga click en el ícono de <b>Configuración</b> y luego en 
    												<b>Editar</b> buzón.',
	'LBL_Compose'         						=> 'Redactar',
	'LBL_Create_Contact'  						=> 'Crear contacto',
	'LBL_CREATE_MAILBOX' 						=> 'Crear Buzón',
	'LBL_Date'        							=> 'Fecha',
	'LBL_Delete'          						=> 'Eliminar',
	'LBL_DELETE_Mailbox' 						=> 'Eliminar Buzón',
	'LBL_Do_Not_Validate_Cert'    				=> 'No validar certificado',
	'LBL_Drafts'								=> 'Borradores',
	'LBL_EMAIL_TEMPLATES_LIST'					=> 'Plantillas de Correo',
	'LBL_FIND'									=> 'Encontrar',
	'LBL_Folders'         						=> 'Carpetas',
	'LBL_Forward'        	 					=> 'Reenviar',
	'LBL_FROM'        							=> 'De',
	'LBL_Go_Back'         						=> 'Regresar',
	'LBL_Imap2'       							=> 'IMAP2',
	'LBL_Imap4'       							=> 'IMAP4',
	'LBL_IN' 									=> 'en',
	'LBL_Like'            						=> 'like',
	'LBL_MAILBOX_DETAILS' 						=> 'Detalles del Buzón',
	'LBL_Mailbox'         						=> 'Buzón',
    'LBL_MAILMANAGER_ADD_Accounts' 				=> 'Agregar cuenta',
    'LBL_MAILMANAGER_ADD_Calendar' 				=> 'Agregar Evento/Tarea',
    'LBL_MAILMANAGER_ADD_Contacts' 				=> 'Agregar Contacto',
    'LBL_MAILMANAGER_ADD_Emails' 				=> 'Adjuntar Correo',
    'LBL_MAILMANAGER_ADD_HelpDesk' 				=> 'Abrir Caso',
    'LBL_MAILMANAGER_ADD_Leads' 				=> 'Agregar Prospecto',
    'LBL_MAILMANAGER_ADD_ModComments' 			=> 'Agregar Comentario',
	'LBL_Mail_Server'     						=> 'Nombre de Servidor de Correo o Dirección IP',
	'LBL_Mark_As_Unread'  						=> 'Marcar como No Leído',
	'LBL_MODULE_DENIED' 						=> 'modulo denegado!',
	'LBL_MODULE_DESCRIPTION' 					=> "El Administrador de Correo es un cliente de correo integrado que permite a los usuarios realizar 
													acciones relacionadas con el CRM con los correos recibidos. Le ayuda a crear Prospectos, Contactos, 
													Cuentas, Casos de Servicio al Cliente y Tareas Pendientes desde los correos que recibe en su buzón. 
													Cuando el correo de remitente corresponde con un registro dentro del CRM, usted puede realizar más
													acciones como: Adjuntar correos, Agregar Tareas Pendientes, Comentar y crear Casos de Servicio al
													Cliente. Adicionalmente, puede redactar, responder, reenviar correos, etc.",
	'LBL_MOVE_TO'								=> 'Mover A...',
	'LBL_Newer'           						=> 'Más Recientes',
	'LBL_Next'            						=> 'siguiente',
 	'LBL_NO_EMAILS_SELECTED' 					=> 'Ningún Correo se ha Seleccionado.',
	'LBL_No_Mails_Found'  						=> 'No se encontraron correos.',
	'LBL_No_Matching_Record_Found' 				=> 'No se encontraron registros relacionados.',
	'LBL_NONE' 									=> 'Ninguno',
	'LBL_No_TLS'      							=> 'Sin TLS',
	'LBL_Older'           						=> 'Más Antiguos',
	'LBL_Outbox'          						=> 'Buzón de Salida del CRM',
	'LBL_Password'             					=> 'Contraseña',
	'LBL_Previous'        						=> 'anterior',
	'LBL_Print' 								=> 'Imprimir',
	'LBL_Protocol'    							=> 'Protocolo',
	'LBL_READ_ACCESS_FOR'						=> 'Permiso de lectura para',
	'LBL_Refresh'         						=> 'Actualizar',
	'LBL_REFRESH_TIME'							=> 'Tiempo de Actualización',
	'LBL_RELATED_RECORDS' 						=> 'Registros Relacionados',
	'LBL_Remove'          						=> 'Remover',
	'LBL_Reply_All'       						=> 'Responder a Todos',
	'LBL_Reply'           						=> 'Responder',
	'LBL_SAVE_BUTTON_LABEL' 					=> 'Guardar',
	'LBL_SAVE_NOW'								=> 'Guardar Ahora',
	'LBL_Search'          						=> 'Buscar',
	'LBL_SELECT_ACCOUNT_TYPE'     				=> 'Seleccionar Tipo de Organización',
	'LBL_SELECT_DOCUMENTS'						=> 'Seleccionar Documentos',
    'LBL_SELECTED_FOLDER' 						=> 'Seleccionar Carpeta',
	'LBL_SELECT_EMAIL_TEMPLATE'					=> 'Seleccionar Plantilla de Correo',
	'LBL_Send'            						=> 'Enviar',
	'LBL_SENT_MAILS' 							=> 'Correos Enviados',
	'LBL_SSL_Options' 							=> 'Opciones de SSL',
	'LBL_SSL'         							=> 'SSL',
	'LBL_SUBJECT'								=> 'Asunto',
	'LBL_TLS'         							=> 'TLS',
	'LBL_TO_ACCOUNTS' 							=> 'A Cuentas',
	'LBL_TO_CONTACTS' 							=> 'A Contactos',
	'LBL_TO_LEADS' 								=> 'A Prospectos',
	'LBL_TO'          							=> 'Para',
	'LBL_TO_USERS' 								=> 'A Usuarios',
	'LBL_Username'             					=> 'Nombre de Usuario',
	'LBL_Validate_Cert'           				=> 'Validar certificado',
	'LBL_WRITE_ACCESS_FOR'						=> 'Permiso de Escritura para',
	'LBL_WRITE_YOUR_COMMENT_HERE' 				=> 'Agregue su comentario aquí ...',
	'LBL_Your_Mailbox_Account' 					=> 'su cuenta de correo',
	'MailManager' 								=> 'Administrador de Correo',
);

$jsLanguageStrings = Array (
	'JS_FUTURE_EVENT_CANNOT_BE_HELD' 			=> 'No Se Puede Completar Evento Futuro',
	'JSLBL_ACCOUNTNAME_CANNOT_EMPTY'			=> 'Nombre de Cuenta no puede estar vacío',
	'JSLBL_ADD_COMMENT'							=> 'Agregar Comentario',
	'JSLBL_Associating'          				=> 'Asociando',
	'JSLBL_ATTACHMENT_NOT_DELETED'				=> 'No se pudo eliminar el Archivo Adjunto',
	'JSLBL_CANNOT_ADD_EMPTY_COMMENT' 			=> 'El Comentario no puede estar vacío',
	'JSLBL_CC'									=> 'Cc: ',
	'JSLBL_Choose_Server_Type'        			=> 'Seleccione el tipo de servidor',
	'JSLBL_DATE'								=> 'Fecha: ',
	'JSLBL_Delete_Confirm'            			=> '¿Quiere eliminar los correos de manera permanente?',
	'JSLBL_Delete'            					=> 'Eliminar',
	'JSLBL_Delete_Mails_Confirm'      			=> '¿Está seguro que quiere eliminar los correos seleccionados?',
	'JSLBL_Deleting'              				=> 'Eliminando',  
	'JSLBL_DRAFT_MAIL_SAVED'					=> 'El Correo ha sido guardado en Borradores',
	'JSLBL_Drafts'								=> 'Borradores',
	'JSLBL_EMAIL_FORMAT_INCORRECT'				=> 'Por favor proporcione una dirección de correo válida',
	'JSLBL_ENTER_SOME_VALUE' 					=> 'Ingrese texto a buscar',
	'JSLBL_Failed_To_Open_Mail'  				=> 'No se pudo abrir el correo',
	'JSLBL_Failed_To_Save_Mail'					=> 'No se pudo guardar el correo',
	'JSLBL_Failed_To_Send_Mail'  				=> 'No se pudo enviar el correo',
	'JSLBL_Fastmail'                  			=> 'Fastmail',
	'JSLBL_FILEUPLOAD_LIMIT_EXCEEDED'			=> 'Se excedió el Tamaño Máximo de Archivos Adjuntos!!',
	'JSLBL_Finding_Relation'     				=> 'Encontrando relación',
	'JSLBL_Find_Relation_Now'    				=> 'Encontrar relación ahora',
	'JSLBL_FORWARD_MESSAGE_TEXT'				=> '---------- Mensaje reenviado ----------',
	'JSLBL_FROM'								=> 'De:',
	'JSLBL_Gmail'                     			=> 'Gmail',
	'JSLBL_LOADING_FOLDERS' 					=> 'Cargando Carpetas...',
	'JSLBL_Loading'              				=> 'Cargando',
	'JSLBL_Loading_Please_Wait'  				=> 'Cargando, Por Favor Espere',
	'JSLBL_MAIL_MOVED'							=> 'Correo(s) movidos',
	'JSLBL_MAIL_SENT'							=> 'Correo Enviado',
	'JSLBL_MOVING'								=> 'Moviendo Correo(s)',
	'JSLBL_NO_EMAILS_SELECTED' 					=> 'Ningún Correo Seleccionado.',
	'JSLBL_NO_MATCH'				  			=> 'No se encontró ningún resultado',
	'JSLBL_Nothing_Found'             			=> 'No se encontró nada',
	'JSLBL_Opening'              				=> 'Abriendo',
	'JSLBL_Other'                     			=> 'Otro',
	'JSLBL_PASSWORD_CANNOT_BE_EMPTY'			=> 'La Contraseña no puede estar vacía',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_MAIL'		=> 'Por favor seleccione al menos un correo',
	'JSLBL_PLEASE_SELECT_ATLEAST_ONE_RECORD'	=> 'Por favor seleccione al menos un registro',
	'JSLBL_Receipents_Warning_Message'			=> 'Por favor seleccione los destinatarios',
	'JSLBL_Recepient_Cannot_Be_Empty' 			=> 'Destinatario (Para) no puede estar vacío',
	'JSLBL_Removing'                  			=> 'Eliminando',
	'JSLBL_Replied'              				=> 'Contestado',
	'JSLBL_SaveWith_EmptySubject'				=> '¿Guardar con el asunto vacío?',
	'JSLBL_Saving_And_Verifying' 				=> 'Guardando y Verificando',
	'JSLBL_Saving'								=> 'Guardando', //Duplicated key-value pairs
	'JSLBL_Search_For_Email'          			=> 'Buscar un correo',
	'JSLBL_Searching_Please_Wait'				=> 'Buscando, Por Favor Espere',
	'JSLBL_Searching'            				=> 'Buscando',
	'JSLBL_Sending'              				=> 'Enviando',
	'JSLBL_SERVERNAME_CANNOT_BE_EMPTY'			=> 'El Nombre del Servidor no puede estar vacío',
	'JSLBL_Settings'             				=> 'Configuración',
	'JSLBL_Subject_Cannot_Be_Empty'     		=> 'El Asunto no puede estar vacío',
	'JSLBL_SUBJECT'								=> 'Asunto: ',
	'JSLBL_TO'									=> 'Para: ',
	'JSLBL_Updating'             				=> 'Actualizando',
	'JSLBL_UPLOAD_CANCEL'						=> 'Cancelando',
	'JSLBL_UPLOAD_DELETE'						=> '[x]',
	'JSLBL_UPLOAD_DROPFILES'					=> 'Arrastre archivos aquí para subir',
	'JSLBL_UPLOAD_FAILED'						=> 'Falló carga',
	'JSLBL_UPLOAD_FILE'							=> 'Subir',
	'JSLBL_USERNAME_CANNOT_BE_EMPTY'			=> 'El Nombre de Usuario no puede estar vacío',
	'JSLBL_Yahoo'								=> 'Yahoo',
	'MailManager' 								=> 'Administrador de Correo',
);

//Special Handling: Mix of language strings are used.
$languageStrings = array_merge($languageStrings, $jsLanguageStrings);
